#!/usr/bin/env bash

start() {
    echo -n "Starting Sugoroku: "
    cd /var/www/sugoroku
    npm start
    return 0
}
stop() {
    killproc sugoroku
    return 0
}
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
esac
